services:
  qiraati-webapp:
    ports:
      - "8080:80" # Map host 8080 to container 80 so you can access it locally
    environment:
      - NODE_ENV=development # Override production env for easier debugging if needed
